### ISSUE TITLE
Update KafkaService

### ISSUE THREAD

**Issue by PLGrudina** [sysgears/akka-spark-pipeline#10]
Make all methods asynchronous in KafkaService

**Comment by proton5000** [comment]
- Move the kafka options to the application.conf file
https://github.com/sysgears/akka-spark-pipeline/pull/16/commits/cacf40374b661d690308f33bcd6e27432d2233e3
- Update guice v4.1.0 to v4.2.2, scala-guice 4.2.1 to v4.2.3
https://github.com/sysgears/akka-spark-pipeline/pull/16/commits/eedd60716abf759f87fe56c554cad405e888ddb9
