### ISSUE TITLE
Add github token, before first app run

### ISSUE THREAD

**Issue by PLGrudina** [sysgears/akka-spark-pipeline#6]
location: object GitHubRequestComposer / private token = <insert personal github token here>

**Comment by Merjey** [comment]
I added an ability to take the GitHub OAuth token from "GitHubOAuthToken" environmental variable. It's still possible to set this token directly inside "object GitHubRequestComposer".

**Comment by alexandervetrov** [comment]
This was implemented and merged.
https://github.com/sysgears/akka-spark-pipeline/pull/17
